[WIP] Allow override on item click to prevent click
Maxr1998/ModernAndroidPreferences pull request #139
Opened 2023-07-06 19:54 UTC by rosenpin

This will allow users to prevent click on specific dialog items.  

Example use case: make certain items premium only and instead of allowing users to tap them, show a premium upgrade dialog

2023-07-07 12:52 UTC, Maxr1998 requested changes
Thanks for the contribution! I left some comments already to look at. If possible, I'd prefer this PR to be split into two, so one for the badge, and one for the selection handling.

2023-07-07 12:52 UTC, Maxr1998 commented on library/src/main/java/de/Maxr1998/modernpreferences/preferences/choice/SelectionAdapter.kt
> +fun interface OnItemClick {
```suggestion
fun interface OnItemClickListener {
```

2023-07-07 12:52 UTC, Maxr1998 commented on library/src/main/java/de/Maxr1998/modernpreferences/preferences/choice/SelectionAdapter.kt
> +    fun shouldPersistClick(item: SelectionItem, index: Int): Boolean
```suggestion
    fun onItemSelected(item: SelectionItem, index: Int): Boolean
```

2023-07-07 12:52 UTC, Maxr1998 commented on library/src/main/java/de/Maxr1998/modernpreferences/preferences/choice/SelectionAdapter.kt
> +                }
Maybe this could instead be handled in the AbstractChoiceDialogPreference.select which is currently abstract. Then, the adapter doesn't have to care about this.

2023-07-07 12:52 UTC, Maxr1998 commented on library/src/main/java/de/Maxr1998/modernpreferences/preferences/choice/AbstractChoiceDialogPreference.kt
> +    var onItemClick: OnItemClick? = null
Move below `autoGeneratedSummary` and above init block.

2023-07-18 20:53 UTC, rosenpin commented on library/src/main/java/de/Maxr1998/modernpreferences/preferences/choice/SelectionAdapter.kt
> +                }
I don't see a clean way to do that.  
The actual updating happens in either `SingleChoiceDialogPreference` or `MultiChoiceDialogPreference` and not in the abstract class.   
I could make `select` return a boolean value of weather it should update or not and then change the code accordingly in the implementations, but it would be more complicated in my opinion.  
For now, I added a `shouldSelect` method to the Abstract class that is being checked before persisting the changes in the respected implementation classes.  
Let me know what you think

2023-07-18 20:53 UTC, rosenpin commented on library/src/main/java/de/Maxr1998/modernpreferences/preferences/choice/SelectionAdapter.kt
> +                }
Ended up moving the `shouldSelect` call inside the adapter to avoid flickering effect triggered by the subsequent `notifyItemChanged`

2023-07-18 20:53 UTC, rosenpin commented on library/src/main/java/de/Maxr1998/modernpreferences/preferences/choice/SelectionAdapter.kt
> +    fun shouldPersistClick(item: SelectionItem, index: Int): Boolean
I changed it but I think `onItemSelected` is a bit misleading as it returns a boolean value

2023-08-27 05:35 UTC, rosenpin commented
Any news about this?

2023-08-27 10:57 UTC, Maxr1998 commented
Apologies, the last few weeks were rather eventful. I'll review this immediately.

2023-08-27 10:58 UTC, Maxr1998 requested changes
The new `shouldSelect` handling looks much better, just a few nitpicks remaining. Otherwise, it's perfect.

2023-08-27 10:58 UTC, Maxr1998 commented on library/src/main/java/de/Maxr1998/modernpreferences/preferences/choice/AbstractChoiceDialogPreference.kt
> +}
This could be moved to a separate file.

2023-08-27 10:58 UTC, Maxr1998 commented on library/src/main/java/de/Maxr1998/modernpreferences/preferences/choice/AbstractChoiceDialogPreference.kt
> +                SelectionAdapter(this@AbstractChoiceDialogPreference, items, allowMultiSelect)
```suggestion
            selectionAdapter = SelectionAdapter(
                this@AbstractChoiceDialogPreference,
                items,
                allowMultiSelect,
            )
```

2023-08-27 10:58 UTC, Maxr1998 commented on library/src/main/java/de/Maxr1998/modernpreferences/preferences/choice/AbstractChoiceDialogPreference.kt
> +
Maybe move this above the `autoGeneratedSummary` property, makes a bit more sense logically.

2023-08-27 13:13 UTC, rosenpin commented
All good 😃  
Thanks for the CR  
I fixed the remaining issues

2023-08-27 16:18 UTC, Maxr1998 approved these changes
Thanks, looking good now!

2023-08-27 16:43 UTC, Maxr1998 commented
Seems like the API schema needs to be updated, I'll do that in a few minutes.

2023-08-27 17:54 UTC, merged