Added option to use badge in dialog preferences
Maxr1998/ModernAndroidPreferences pull request #140
Opened 2023-07-18 21:13 UTC by rosenpin

2023-07-24 21:55 UTC, rosenpin commented
Accidentally added option to change badge color as well, you can drop the last commit if you don't want to include that

2023-08-27 16:24 UTC, Maxr1998 requested changes
If it's ok for you, I would do some formatting tweaks myself after you fixed my one comment here, that's easier than having to write a lot of suggestions in this review.

2023-08-28 05:33 UTC, rosenpin commented on library/src/main/java/de/Maxr1998/modernpreferences/helpers/Badge.kt
> +)
I think it might be worth the breakage, otherwise we could end up with many random badge related flags in a Preference, which is kind of ugly  
For example, we might want to allow text change/icons in badge in the future  
This change only requires a small adjustment in the apps that use the library, just wrap the text in a badge object

2023-08-28 05:34 UTC, rosenpin commented on library/src/main/java/de/Maxr1998/modernpreferences/helpers/Badge.kt
> +)
How about keeping the original argument but marking it as deprecated and adding the new Badge object as well?

2023-08-28 05:34 UTC, rosenpin commented
> If it's ok for you, I would do some formatting tweaks myself after you fixed my one comment here, that's easier than having to write a lot of suggestions in this review.

Sure sounds good

2023-08-28 08:59 UTC, Maxr1998 commented on library/src/main/java/de/Maxr1998/modernpreferences/helpers/Badge.kt
> +)
Hmm, I do see that point. Three individual properties would be fine for me, but an object definitely future proofs for further extension. Let's go with the deprecation plan then.

2023-08-28 09:46 UTC, Maxr1998 commented
Btw, you might need to rebase your PR onto the latest master to pass the updated check workflows.

2023-08-28 13:13 UTC, rosenpin commented on library/src/main/java/de/Maxr1998/modernpreferences/helpers/Badge.kt
> +)
Cool  
To avoid the breakage we'll just need to settle on a different name for the `Badge` member, I went with `badgeInfo` but if you have a better idea I'll change it

2023-08-28 13:13 UTC, rosenpin commented
> Btw, you might need to rebase your PR onto the latest master to pass the updated check workflows.

Thanks, done

2023-09-03 18:42 UTC, rosenpin commented
🙃

2023-09-04 22:08 UTC, Maxr1998 approved these changes
Sorry for taking so long, my short-term memory has been bad lately, so I simply forgot to finish the review. I ended up doing more changes to the PR than planned, not just formatting, but also some other small tweaks. I hope you don't mind the commit spam (I'll squash it anyways), I mostly wanted to document all my changes for you to see.

2023-09-04 22:12 UTC, Maxr1998 commented
I think we might need another rebase to drop the already applied commits :grimacing:

If that's ok for you, I'll do that, and then merge.

2023-09-05 05:31 UTC, rosenpin commented
Thanks man you're great! It's looking much better now, sorry for not making it easier for you  
And of course, you can go ahead and rebase it as much as you want, it's your repo :P

2023-09-05 10:36 UTC, merged